version: '2.1'
services:
  t-modile-ad-stand:
    image: jboss/wildfly:12.0.0.Final
    container_name: t-modile-ad-stand
    ports:
      - "8180:8080"
    external_links:
      - tmobile_t-activemq
    volumes:
      - ./target/TMobileAdStand.war:/opt/jboss/wildfly/standalone/deployments/TMobileAdStand.war
    networks:
      - t_network

networks:
  t_network:
    external:
      name: tmobile_t_network


